version: '3'
services:
    app:
      container_name: testProj
      image: ver3:latest
      restart: always
      build: .
      env_file:
       - ./.env
      ports:
      - '5500:5500'
      links:
      - mongo

            
    mongo:
      container_name: mongo
      image: mongo
      restart: always
      # volumes:
      # - ./data:/data/db
      ports:
      - '27017:27017'

    # mongo-express: 
    #   container_name: mongo-express
    #   image: mongo-express
    #   ports: 
    #    - '8083:8081'
    #   networks:
    #    - myNet
 


networks:
  myNet:
    driver: bridge
      

  